import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {io} from 'socket.io-client';
test('cadastro, autorização, amizade, canais, mensagens e sinalização',async()=>{
const dir=await mkdtemp(join(tmpdir(),'iliacord-test-'));const child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3099',DATA_DIR:dir,ALLOWED_ORIGINS:'http://localhost:3099'},stdio:['ignore','pipe','pipe']});const sockets=[];
try{await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',()=>reject(Error('Server exited')))});
const req=async(path,body,token,method)=>{const r=await fetch('http://localhost:3099/api'+path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json().catch(()=>null)}};
const signup=async name=>(await req('/auth',{name,password:'test-password-123',register:true})).data;
const a=await signup('alice'),b=await signup('bruno'),c=await signup('carla');assert.ok(a.token&&b.token);assert.equal((await req('/auth',{name:'alice',password:'incorrect',register:false})).status,401);assert.equal((await req('/auth',{name:'alice',password:'test-password-123',register:true})).status,409);
await req('/friends',{name:'bruno'},a.token);await req('/friends/respond',{uid:a.user.id,accept:true},b.token);assert.equal((await req('/state',null,a.token)).data.friends[0].status,'accepted');
const sid=(await req('/servers',{name:'Teste'},a.token)).data.id;const state=(await req('/state',null,a.token)).data;const channel=state.channels.find(x=>x.type==='text');const voice=state.channels.find(x=>x.type==='voice');assert.equal((await req('/messages/'+channel.id,null,b.token)).status,403);await req('/join',{code:state.servers[0].invite},b.token);assert.equal((await req('/messages/'+channel.id,null,b.token)).status,200);assert.equal((await req('/channels',{sid,name:'hack'},b.token)).status,403);
const connect=async token=>{const s=io('http://localhost:3099',{auth:{token},transports:['websocket']});sockets.push(s);await new Promise((res,rej)=>{s.on('connect',res);s.on('connect_error',rej)});return s};const sa=await connect(a.token),sb=await connect(b.token),sc=await connect(c.token);const emit=(s,e,b)=>new Promise((resolve,reject)=>s.timeout(3000).emit(e,b,(err,r)=>err?reject(err):resolve(r)));
assert.ok((await emit(sc,'room',channel.id)).error);await emit(sa,'room',channel.id);await emit(sb,'room',channel.id);assert.equal((await emit(sa,'send',{room:channel.id,body:'Olá, Bruno!'})).ok,true);const msgs=(await req('/messages/'+channel.id,null,b.token)).data;assert.equal(msgs[0].body,'Olá, Bruno!');await req('/messages/'+msgs[0].id,null,b.token,'DELETE');assert.equal((await req('/messages/'+channel.id,null,a.token)).data.length,1);await req('/reactions',{id:msgs[0].id,emoji:'❤️'},b.token);assert.equal((await req('/messages/'+channel.id,null,a.token)).data[0].reactions[0].count,1);
assert.equal((await emit(sa,'voice-join',voice.id)).peers.length,0);assert.equal((await emit(sb,'voice-join',voice.id)).peers.length,1);assert.ok((await emit(sc,'voice-join',voice.id)).error);const signal=new Promise(res=>sb.once('signal',res));sa.emit('signal',{to:sb.id,signal:{description:{type:'offer',sdp:'test'}}});assert.equal((await signal).from,sa.id);
await req('/profile',{display:'Alice nova',avatar:'',color:'#aabbcc',bio:'Oi',pronouns:'ela/dela'},a.token,'PATCH');assert.equal((await req('/state',null,a.token)).data.user.display,'Alice nova');assert.equal((await req('/profile',{avatar:'data:text/html;base64,abc'},a.token,'PATCH')).status,400);

const code=state.servers[0].invite;
const preview=(await req('/invites/'+code)).data;
assert.equal(preview.total,2);assert.equal(preview.online,2);assert.equal(preview.offline,0);
assert.equal(preview.owner,undefined);assert.equal(preview.members,undefined);
assert.equal((await req('/invites/not-valid')).status,404);
const photo='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1cAAAAASUVORK5CYII=';
assert.equal((await req('/server-icons/'+sid,{image:photo},b.token,'PATCH')).status,403);
assert.equal((await req('/server-icons/'+sid,{image:photo},a.token,'PATCH')).status,200);
assert.equal((await req('/state',null,a.token)).data.servers[0].photo,photo);
const page=await fetch('http://localhost:3099/invite/'+code);const html=await page.text();assert.equal(page.status,200);assert.ok(html.includes('og:title'));assert.ok(html.includes('2 online'));assert.ok(html.includes('/?invite='+code));
const img=await fetch('http://localhost:3099/invite/'+code+'/icon');assert.equal(img.headers.get('content-type'),'image/png');
assert.equal((await req('/join',{code},b.token)).status,200);assert.equal((await req('/invites/'+code)).data.total,2);

assert.equal((await req('/appearance',{decoration:'angel'},a.token,'PATCH')).status,403);
assert.equal((await req('/plus/acquire',{combo:'celestial'},a.token)).status,200);
await req('/plus/acquire',{combo:'celestial'},a.token);
assert.deepEqual((await req('/plus',null,a.token)).data.owned,['celestial']);
assert.equal((await req('/appearance',{decoration:'angel',profileEffect:'stardust',nameEffect:'galaxy',banner:photo,color2:'#445566',gradientAngle:200},a.token,'PATCH')).status,200);
assert.equal((await req('/appearance',{banner:'javascript:alert(1)'},a.token,'PATCH')).status,400);
assert.equal((await req('/state',null,b.token)).data.friends[0].user.decoration,'angel');
await req('/profile',{display:'Alice',avatar:''},a.token,'PATCH');
assert.equal((await req('/state',null,a.token)).data.user.decoration,'angel');
const upload=async(token,mime='image/png')=>fetch('http://localhost:3099/api/media?'+new URLSearchParams({room:channel.id,mime,name:'print.png'}),{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/octet-stream'},body:Buffer.from(photo.split(',')[1],'base64')});
assert.equal((await upload(c.token)).status,403);
assert.equal((await upload(a.token,'text/html')).status,400);
const uploaded=await (await upload(a.token)).json();assert.ok(uploaded.id);
assert.ok((await emit(sb,'send',{room:channel.id,body:'',attachments:[uploaded.id]})).error);
assert.equal((await emit(sa,'send',{room:channel.id,body:'print',attachments:[uploaded.id]})).ok,true);
const notice=new Promise(resolve=>sb.once('notification',resolve));let leaked=false;sc.once('notification',()=>leaked=true);
assert.equal((await emit(sa,'send',{room:channel.id,body:'sem espera'})).ok,true);
const notification=await notice;assert.equal(notification.room,channel.id);assert.equal(notification.user.id,a.user.id);assert.equal(notification.user.hash,undefined);assert.equal(leaked,false);
const attached=(await req('/messages/'+channel.id,null,b.token)).data.find(m=>m.attachments.length);assert.equal(attached.attachments[0].name,'print.png');
const download=await fetch('http://localhost:3099/api/media/'+uploaded.id,{headers:{Authorization:'Bearer '+b.token}});assert.equal(download.status,200);assert.deepEqual(Buffer.from(await download.arrayBuffer()),Buffer.from(photo.split(',')[1],'base64'));
assert.equal((await fetch('http://localhost:3099/api/media/'+uploaded.id,{headers:{Authorization:'Bearer '+c.token}})).status,404);
await req('/messages/'+attached.id,null,a.token,'DELETE');
assert.equal((await fetch('http://localhost:3099/api/media/'+uploaded.id,{headers:{Authorization:'Bearer '+a.token}})).status,404);
await req('/logout',{},a.token);assert.equal((await req('/state',null,a.token)).status,401);
}finally{sockets.forEach(s=>s.disconnect());child.kill();await new Promise(res=>child.once('exit',res));await rm(dir,{recursive:true,force:true})}
});
