export function makeNotifications(ctx){
 const unread=new Map();let sound=localStorage.getItem('ilia-notification-sound')!=='off',audio,lastSound=0;
 const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 document.addEventListener('pointerdown',()=>{try{audio||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}},{once:true});
 function chime(){if(!sound||!audio||Date.now()-lastSound<1500)return;lastSound=Date.now();for(const [frequency,delay] of [[660,0],[880,.12]]){const oscillator=audio.createOscillator(),gain=audio.createGain(),start=audio.currentTime+delay;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.08,start+.02);gain.gain.exponentialRampToValueAtTime(.001,start+.24);oscillator.connect(gain).connect(audio.destination);oscillator.start(start);oscillator.stop(start+.25);}}
 function open(n){unread.delete(n.room);document.querySelectorAll('.message-notice').forEach(e=>e.remove());ctx.open(n);paint();window.focus();}
 function paint(){const rail=document.querySelector('#notification-rail');if(!rail)return;rail.innerHTML=[...unread.values()].map(n=>`<button class="unread-person" data-notice="${escape(n.room)}" title="${escape(n.user.display)} · ${n.count} mensagens">${ctx.av(n.user)}<b>${n.count>99?'99+':n.count}</b></button>`).join('');rail.querySelectorAll('[data-notice]').forEach(b=>b.onclick=()=>open(unread.get(b.dataset.notice)));document.title=unread.size?`(${[...unread.values()].reduce((a,n)=>a+n.count,0)}) IliaCord`:'IliaCord';}
 async function receive(n){if(n.user.id===ctx.user()?.id)return;if(ctx.room()===n.room&&document.visibilityState==='visible'&&document.hasFocus())return;const previous=unread.get(n.room);unread.set(n.room,{...n,count:(previous?.count||0)+1});paint();chime();let stack=document.querySelector('#message-notices');if(!stack){stack=document.createElement('div');stack.id='message-notices';stack.setAttribute('aria-live','polite');document.body.append(stack);}const button=document.createElement('button');button.className='message-notice';button.innerHTML=ctx.av(n.user)+`<span><strong>${escape(n.user.display)}</strong><small>${escape(n.body||'Enviou um anexo')}</small></span><span>↗</span>`;button.onclick=()=>open(n);stack.prepend(button);while(stack.children.length>3)stack.lastChild.remove();setTimeout(()=>button.remove(),8000);
  if(document.visibilityState==='hidden'&&'Notification'in window&&Notification.permission==='granted'){try{const options={body:n.body||'Enviou um anexo',icon:n.user.avatar||'/ilia-icon-192.png',tag:n.room,data:{url:'/?chat='+encodeURIComponent(n.room)},silent:true};const registration=await navigator.serviceWorker?.getRegistration();if(registration)await registration.showNotification(n.user.display,options);else{const notification=new Notification(n.user.display,options);notification.onclick=()=>{open(n);notification.close();};}}catch{}}
 }
 function settings(){ctx.showModal('Notificações',`<p>Avatares com mensagens não lidas aparecem abaixo do IliaCord. Clique para abrir a conversa.</p><label><input id="notice-sound" type="checkbox" ${sound?'checked':''}> Som de mensagem</label><button type="button" id="desktop-notices" class="secondary">Ativar avisos do navegador</button><p><small>Os avisos funcionam enquanto o site ou app estiver aberto. O navegador pode silenciar sons até você interagir com a página.</small></p>`);document.querySelector('#notice-sound').onchange=e=>{sound=e.target.checked;localStorage.setItem('ilia-notification-sound',sound?'on':'off');};document.querySelector('#desktop-notices').onclick=async()=>{if(!('Notification'in window))return ctx.toast('Este navegador não oferece avisos de sistema.');const result=await Notification.requestPermission();ctx.toast(result==='granted'?'Avisos ativados.':'Os avisos dentro do app continuam disponíveis.');};}
 return {receive,paint,settings,read(room){unread.delete(room);paint();},clear(){unread.clear();paint();document.querySelector('#message-notices')?.remove();}};
}
